### ISSUE TITLE
getting double the number of concrete classes 

### ISSUE THREAD

**Issue by Yawarmurtaza** [servicetitan/lazy-proxy-unity#8]
Hi,
I have an interface that is implemented by 2 classes. I used named instance registration:
```
using (IUnityContainer container = new UnityContainer())
{
    container.RegisterLazy<IController, Controller>("Controller");
    container.RegisterLazy<IController, MyController>("MyController");
  
    var objs = container.ResolveAll<IController>();

    foreach (IController controller in objs)
    {
        string s = controller.Name;
    }
}
```

Now, the reason I get 4 implementation in the objs object is because in the Initialise method we are registering the same type with its implementation twice:

```
protected override void Initialize()
{
    string registrationName = Guid.NewGuid().ToString();

    Context.Container.RegisterType(_typeFrom, _typeTo, _name, _getLifetimeManager(), _injectionMembers);
    Context.Container.RegisterType(_typeFrom, _typeTo, registrationName, _getLifetimeManager(), _injectionMembers); // this is proxy registration... which is causing me trouble --- why we need this?

    Context.Policies.Set(_typeFrom, _name, typeof(ResolveDelegateFactory),
        (ResolveDelegateFactory)((ref BuilderContext _) =>
           (ref BuilderContext c) =>
           {
               IUnityContainer container = c.Container;
               Type type = c.RegistrationType;
               ResolverOverride[] overrides = c.Overrides;

               return LazyProxyBuilder.CreateInstance(type,
                   //() => container.Resolve(type, registrationName, overrides)
                   () => container.Resolve(type, _name)
               );
           })
    );
}
```
Can someone please help me understand why we have double registration for each type?

Thanks!

**Comment by hypercodeplace** [comment]
Hi @Yawarmurtaza 

As you noticed, the implementation of LazyProxy.Unity uses double regular registration per one "lazy" registration. The first registration is a real one and registered with a unique name, the second one is a proxy registration, that registered with a name used for the original registration. So in your example, we have 4 registration:

1. IController -> Controller (with "Controller" name);
2. IController -> Controller (with GUID name);
3. IController -> MyController (with "MyController" name);
4. IController -> MyController (with GUID name);

So you have all these 4 services when using `ResolveAll` because Unity resolves all registrations of the same interface independently from the name of registration (this is a specific of Unity).

If you want to get only real registrations you can filter out the enumeration by assembly name of the type. This is a work-around,  there is no better way yet.

**Comment by Yawarmurtaza** [comment]
Thanks @hypercodeplace for suggested workaround. Its not ideal but yes it works. The issue here is maintainability and for new devs to understand this issue is a bit twisted. 
Regards
Yawar
